# Generated by Django 5.2.14 on 2026-05-18 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sector', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'db_table': 'careers_career',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('PUBLIC_UNIVERSITY', 'Public University'), ('PRIVATE_UNIVERSITY', 'Private University'), ('TECHNICAL', 'Technical Institute')], db_index=True, max_length=30)),
                ('website', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'careers_institution',
            },
        ),
        migrations.CreateModel(
            name='CareerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_weight', models.DecimalField(decimal_places=4, default=1.0, help_text='How strongly this tag predicts success in this career', max_digits=5)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.career')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tag')),
            ],
            options={
                'db_table': 'careers_career_tag',
            },
        ),
        migrations.AddField(
            model_name='career',
            name='tags',
            field=models.ManyToManyField(related_name='careers', through='careers.CareerTag', to='core.tag'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuccps_code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('qualification', models.CharField(choices=[('DEGREE', 'Degree'), ('DIPLOMA', 'Diploma'), ('CERTIFICATE', 'Certificate')], max_length=30)),
                ('duration_years', models.PositiveSmallIntegerField(default=4)),
                ('career', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='careers.career')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='careers.institution')),
            ],
            options={
                'db_table': 'careers_course',
            },
        ),
        migrations.CreateModel(
            name='CutoffCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_number', models.PositiveSmallIntegerField()),
                ('cutoff_points', models.DecimalField(decimal_places=3, max_digits=5)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutoff_clusters', to='careers.course')),
            ],
            options={
                'db_table': 'careers_cutoff_cluster',
            },
        ),
        migrations.CreateModel(
            name='SubjectRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('COMPULSORY', 'Compulsory'), ('ALTERNATIVE', 'Alternative'), ('OPTIONAL', 'Optional')], max_length=20)),
                ('minimum_grade', models.CharField(blank=True, max_length=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_requirements', to='careers.course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.subject')),
            ],
            options={
                'db_table': 'careers_subject_requirement',
            },
        ),
        migrations.AddConstraint(
            model_name='careertag',
            constraint=models.UniqueConstraint(fields=('career', 'tag'), name='uq_careertag'),
        ),
        migrations.AddConstraint(
            model_name='cutoffcluster',
            constraint=models.UniqueConstraint(fields=('course', 'cluster_number', 'year'), name='uq_cutoff_course_cluster_year'),
        ),
        migrations.AddConstraint(
            model_name='subjectrequirement',
            constraint=models.UniqueConstraint(fields=('course', 'subject'), name='uq_subjreq_course_subject'),
        ),
    ]
