# Generated by Django 5.2.14 on 2026-07-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='kuccps_code',
            new_name='code',
        ),
        migrations.AddField(
            model_name='institution',
            name='country',
            field=models.CharField(db_index=True, default='Kenya', max_length=100),
        ),
    ]
