# Generated by Django 5.2.14 on 2026-07-08 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_rename_kuccps_code_course_code_institution_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutoffcluster',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cutoff_clusters', to='careers.institution'),
        ),
    ]
