# Generated by Django 5.2.14 on 2026-07-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_cutoffcluster_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
