# Generated by Django 5.2.14 on 2026-07-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_alter_course_slug'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cutoffcluster',
            name='uq_cutoff_course_cluster_year',
        ),
        migrations.AddConstraint(
            model_name='cutoffcluster',
            constraint=models.UniqueConstraint(fields=('course', 'cluster_number', 'year', 'institution'), name='uq_cutoff_course_cluster_year_institution'),
        ),
    ]
