# Generated by Django 5.2.14 on 2026-07-14 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_careerpreference_rank_and_more'),
        ('careers', '0005_remove_cutoffcluster_uq_cutoff_course_cluster_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPsychometricQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Questions are presented in ascending order.', verbose_name='Display order')),
                ('prompt', models.TextField(verbose_name='Question text')),
                ('help_text', models.TextField(blank=True, help_text='Optional clarification shown below the question prompt.', verbose_name='Help text')),
                ('question_type', models.CharField(choices=[('SINGLE_CHOICE', 'Single Choice'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('MULTI_SELECT', 'Multiple Selection'), ('NUMERIC', 'Numeric'), ('SHORT_TEXT', 'Short Text'), ('LONG_TEXT', 'Long Text')], default='SINGLE_CHOICE', max_length=20, verbose_name='Question type')),
                ('required', models.BooleanField(default=True, help_text='If True, the user cannot advance without answering.', verbose_name='Required')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Type-specific configuration. Examples:\n  NUMERIC:    {"min": 0, "max": 10, "step": 1, "unit": "years"}\n  SHORT_TEXT: {"max_length": 255, "placeholder": "Your answer…"}\n  LONG_TEXT:  {"max_length": 2000}', verbose_name='Metadata')),
            ],
            options={
                'verbose_name': 'Career Psychometric Question',
                'verbose_name_plural': 'Career Psychometric Questions',
                'ordering': ['questionnaire', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CareerPsychometricChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='What the user sees.', max_length=512, verbose_name='Display label')),
                ('value', models.CharField(help_text='What is saved in the response. Should be stable (e.g. a slug or key).', max_length=100, verbose_name='Stored value')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Display order')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='careers.careerpsychometricquestion', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Career Psychometric Choice',
                'verbose_name_plural': 'Career Psychometric Choices',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CareerPsychometricResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='IN_PROGRESS', max_length=20, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychometric_responses', to='accounts.userprofile', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Career Psychometric Response',
                'verbose_name_plural': 'Career Psychometric Responses',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CareerPsychometricResponseAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, default='', help_text='Used for SHORT_TEXT and LONG_TEXT questions.', verbose_name='Text answer')),
                ('numeric_answer', models.DecimalField(blank=True, decimal_places=4, help_text='Used for NUMERIC questions.', max_digits=12, null=True, verbose_name='Numeric answer')),
                ('answered_at', models.DateTimeField(auto_now=True, verbose_name='Last updated at')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_answers', to='careers.careerpsychometricquestion', verbose_name='Question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='careers.careerpsychometricresponse', verbose_name='Response')),
                ('selected_choices', models.ManyToManyField(blank=True, help_text='Used for SINGLE_CHOICE, MULTIPLE_CHOICE, and MULTI_SELECT.', related_name='response_answers', to='careers.careerpsychometricchoice', verbose_name='Selected choices')),
            ],
            options={
                'verbose_name': 'Career Psychometric Response Answer',
                'verbose_name_plural': 'Career Psychometric Response Answers',
                'ordering': ['response', 'question__order'],
            },
        ),
        migrations.CreateModel(
            name='CareerPsychometricTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Test name')),
                ('slug', models.SlugField(help_text='Auto-generated from name. Used in URLs.', max_length=255, unique=True, verbose_name='URL slug')),
                ('description', models.TextField(help_text='Shown on the test selection card. Keep concise (2-3 sentences).', verbose_name='Short description')),
                ('instructions', models.TextField(blank=True, help_text='Displayed to the user before they begin. Can include guidance on approach.', verbose_name='Instructions')),
                ('category', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='basic', max_length=20, verbose_name='Difficulty category')),
                ('estimated_duration', models.PositiveSmallIntegerField(help_text='Shown on the card. Should reflect median completion time.', verbose_name='Estimated duration (minutes)')),
                ('total_questions', models.PositiveSmallIntegerField(default=0, help_text='Denormalised count. Updated automatically via signal or save().', verbose_name='Total questions')),
                ('is_active', models.BooleanField(default=True, help_text='Only active tests are shown to users.', verbose_name='Active')),
                ('is_premium', models.BooleanField(default=False, help_text='If True, requires a paid subscription to attempt. UI placeholder is in place.', verbose_name='Premium only')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Career Psychometric Test',
                'verbose_name_plural': 'Career Psychometric Tests',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['is_active', 'category'], name='careers_car_is_acti_1aa718_idx'), models.Index(fields=['slug'], name='careers_car_slug_3f5324_idx')],
            },
        ),
        migrations.AddField(
            model_name='careerpsychometricresponse',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='careers.careerpsychometrictest', verbose_name='Test'),
        ),
        migrations.AddField(
            model_name='careerpsychometricquestion',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='careers.careerpsychometrictest', verbose_name='Test'),
        ),
        migrations.CreateModel(
            name='CareerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generated at')),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='Tracks async recommendation generation pipeline state.', max_length=20, verbose_name='Processing status')),
                ('recommendation_summary', models.TextField(blank=True, help_text='Human-readable summary of the top recommendation. Suitable for email.', verbose_name='Summary')),
                ('recommendation_details', models.JSONField(blank=True, default=dict, help_text='Full structured recommendation output. Schema example:\n{\n  "careers": [{"slug": "software-engineer", "match_pct": 88, "rank": 1, "reason": "…"}],\n  "insights": [{"title": "…", "body": "…", "score": 78}]\n}', verbose_name='Recommendation details')),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='Algorithm confidence in this recommendation set.', max_digits=5, null=True, verbose_name='Confidence score (0–100)')),
                ('algorithm_version', models.CharField(blank=True, default='v1', help_text='Tracks which recommendation algorithm produced this result. Enables later A/B comparison or version filtering.', max_length=50, verbose_name='Algorithm version')),
                ('email_sent', models.BooleanField(default=False, help_text='True once the recommendation email has been dispatched to the user.', verbose_name='Email sent')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Email sent at')),
                ('response', models.ForeignKey(blank=True, help_text='The psychometric response that triggered this recommendation. Nullable so recommendations can be regenerated independently.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='careers.careerpsychometricresponse', verbose_name='Source response')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_recommendations', to='accounts.userprofile', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Career Recommendation',
                'verbose_name_plural': 'Career Recommendations',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='careerpsychometricchoice',
            index=models.Index(fields=['question', 'order'], name='careers_car_questio_5b19ff_idx'),
        ),
        migrations.AddIndex(
            model_name='careerpsychometricresponseanswer',
            index=models.Index(fields=['response'], name='careers_car_respons_d0ee71_idx'),
        ),
        migrations.AddIndex(
            model_name='careerpsychometricresponseanswer',
            index=models.Index(fields=['question'], name='careers_car_questio_2f2976_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='careerpsychometricresponseanswer',
            unique_together={('response', 'question')},
        ),
        migrations.AddIndex(
            model_name='careerpsychometricresponse',
            index=models.Index(fields=['user', 'questionnaire', 'status'], name='careers_car_user_id_0f953e_idx'),
        ),
        migrations.AddIndex(
            model_name='careerpsychometricresponse',
            index=models.Index(fields=['user', 'status'], name='careers_car_user_id_41db48_idx'),
        ),
        migrations.AddIndex(
            model_name='careerpsychometricquestion',
            index=models.Index(fields=['questionnaire', 'order'], name='careers_car_questio_d005ea_idx'),
        ),
        migrations.AddIndex(
            model_name='careerpsychometricquestion',
            index=models.Index(fields=['questionnaire', 'is_active'], name='careers_car_questio_38cfcd_idx'),
        ),
        migrations.AddIndex(
            model_name='careerrecommendation',
            index=models.Index(fields=['user', 'processing_status'], name='careers_car_user_id_809ab0_idx'),
        ),
        migrations.AddIndex(
            model_name='careerrecommendation',
            index=models.Index(fields=['user', '-generated_at'], name='careers_car_user_id_7b6410_idx'),
        ),
        migrations.AddIndex(
            model_name='careerrecommendation',
            index=models.Index(fields=['response'], name='careers_car_respons_204ca9_idx'),
        ),
    ]
