# Generated by Django 5.2.14 on 2026-07-20 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_notification_settings_and_more'),
        ('careers', '0006_careerpsychometricquestion_careerpsychometricchoice_and_more'),
        ('core', '0002_alter_tag_order_alter_tag_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=20, unique=True)),
                ('engine_type', models.CharField(choices=[('RULE_BASED', 'Rule-Based / Weighted Graph'), ('HYBRID', 'Hybrid'), ('LEARNING_TO_RANK', 'Learning To Rank'), ('EMBEDDING', 'Embedding-Based'), ('GRAPH_NEURAL_NET', 'Graph Neural Network')], max_length=20)),
                ('parameters', models.JSONField(blank=True, help_text='Snapshot of weights/config this version was released with', null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Exactly one engine version is active for new jobs at a time')),
                ('is_shadow', models.BooleanField(default=False, help_text='Runs in parallel for evaluation; never user-facing')),
                ('description', models.TextField(blank=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('deprecated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recsys_engine_version',
                'indexes': [models.Index(fields=['is_active'], name='recsys_engi_is_acti_3ddcb3_idx'), models.Index(fields=['engine_type', 'is_active'], name='recsys_engi_engine__add1c3_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeatureRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100, unique=True)),
                ('feature_type', models.CharField(choices=[('NUMERIC', 'Numeric'), ('CATEGORICAL', 'Categorical'), ('BOOLEAN', 'Boolean'), ('VECTOR', 'Vector'), ('TEXT', 'Text')], max_length=20)),
                ('source_table', models.CharField(help_text="Primary table this feature is derived from, e.g. 'UserTagVector'", max_length=100)),
                ('compute_function', models.CharField(help_text="Dotted path, e.g. 'careers.services.features.subject_affinity'", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recsys_feature_registry',
                'indexes': [models.Index(fields=['feature_type', 'is_active'], name='recsys_feat_feature_c6cd00_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecommendationExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation_type', models.CharField(choices=[('TAG_CONTRIBUTION', 'Tag Contribution Breakdown'), ('SUBJECT_MATCH', 'Subject Match'), ('PSYCHOMETRIC_MATCH', 'Psychometric Match'), ('PEER_COMPARISON', 'Peer Comparison'), ('NARRATIVE', 'Natural-Language Narrative')], max_length=20)),
                ('explanation_data', models.JSONField()),
                ('explanation_version', models.CharField(default='1.0.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='careers.careerrecommendation')),
            ],
            options={
                'db_table': 'recsys_recommendation_explanation',
                'indexes': [models.Index(fields=['recommendation', 'explanation_type'], name='recsys_reco_recomme_68b117_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('INTERESTED', 'Interested'), ('NOT_INTERESTED', 'Not Interested'), ('ALREADY_PURSUING', 'Already Pursuing'), ('NOT_RELEVANT', 'Not Relevant To Me'), ('INACCURATE', 'Inaccurate Match')], db_index=True, max_length=20)),
                ('feedback_score', models.DecimalField(blank=True, decimal_places=2, help_text='Optional explicit rating, e.g. -1.0 to 1.0 or 1-5', max_digits=4, null=True)),
                ('context', models.JSONField(blank=True, help_text='Free-form context, e.g. which UI surface this was collected from', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='careers.career')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_feedback', to='accounts.userprofile')),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='careers.careerrecommendation')),
            ],
            options={
                'db_table': 'recsys_recommendation_feedback',
                'indexes': [models.Index(fields=['profile', 'career'], name='recsys_reco_profile_62200d_idx'), models.Index(fields=['career', 'feedback_type'], name='recsys_reco_career__90f3dd_idx'), models.Index(fields=['recommendation'], name='recsys_reco_recomme_32dfbd_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('VIEW', 'View'), ('CLICK', 'Click'), ('SAVE', 'Save'), ('SHARE', 'Share'), ('DISMISS', 'Dismiss'), ('APPLY', 'Apply / Follow Through')], db_index=True, max_length=10)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='careers.career')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_interactions', to='accounts.userprofile')),
                ('recommendation', models.ForeignKey(blank=True, help_text='If this interaction happened in the context of a specific recommendation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='careers.careerrecommendation')),
            ],
            options={
                'db_table': 'recsys_user_interaction',
                'indexes': [models.Index(fields=['profile', 'career', 'interaction_type'], name='recsys_user_profile_95a95d_idx'), models.Index(fields=['career', 'interaction_type', 'occurred_at'], name='recsys_user_career__3d1f4c_idx'), models.Index(fields=['session_id'], name='recsys_user_session_deacb4_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserTagVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affinity_score', models.DecimalField(decimal_places=4, default=0, help_text='0.0-1.0 aggregated affinity for this tag', max_digits=6)),
                ('confidence', models.DecimalField(decimal_places=4, default=0, help_text='0.0-1.0 confidence in affinity_score (see Part 4 methodology)', max_digits=5)),
                ('evidence_count', models.PositiveIntegerField(default=0, help_text='How many distinct evidence sources contributed to this score')),
                ('algorithm_version', models.CharField(blank=True, help_text='Which engine version last computed this row', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_vector_entries', to='accounts.userprofile')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vector_entries', to='core.tag')),
            ],
            options={
                'db_table': 'recsys_user_tag_vector',
                'indexes': [models.Index(fields=['profile', '-affinity_score'], name='recsys_user_profile_125a67_idx'), models.Index(fields=['tag', '-affinity_score'], name='recsys_user_tag_id_2e4697_idx'), models.Index(fields=['profile', 'last_updated'], name='recsys_user_profile_3d0a5e_idx')],
                'constraints': [models.UniqueConstraint(fields=('profile', 'tag'), name='uq_usertagvector_profile_tag')],
            },
        ),
    ]
