# Generated by Django 5.2.14 on 2026-07-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_updated_at_and_more'),
        ('careers', '0007_engineversion_featureregistry_and_more'),
        ('core', '0003_tagrelationship_tagsourcemetadata'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='careerrecommendation',
            index=models.Index(fields=['user', 'algorithm_version', 'generated_at'], name='careers_car_user_id_966ea1_idx'),
        ),
        migrations.AddIndex(
            model_name='careertag',
            index=models.Index(fields=['career', 'tag'], name='careers_car_career__89d6ea_idx'),
        ),
        migrations.AddIndex(
            model_name='careertag',
            index=models.Index(fields=['tag', '-recommendation_weight'], name='careers_car_tag_id_48157c_idx'),
        ),
    ]
