# Generated by Django 5.2.14 on 2026-05-18 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('max_score', models.DecimalField(decimal_places=2, help_text='Computed ceiling — updated when questions change', max_digits=8)),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, help_text='NULL = untimed. Enables future timed tests.', null=True)),
                ('is_randomised', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assessments_questionnaire',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice (single answer)'), ('MULTI', 'Multiple Select (many correct)'), ('TEXT', 'Free text'), ('NUMERIC', 'Numeric / Range'), ('LIKERT', 'Likert Scale (psychometric)'), ('RANKING', 'Drag-to-rank')], db_index=True, max_length=20)),
                ('question_text', models.TextField()),
                ('explanation', models.TextField(blank=True, help_text='Post-answer feedback shown to user')),
                ('weight', models.DecimalField(decimal_places=4, default=1.0, help_text='Multiplier for this question in total score', max_digits=6)),
                ('max_points', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('randomisation_group', models.CharField(blank=True, help_text='Questions in same group are shuffled together', max_length=50)),
                ('is_required', models.BooleanField(default=True)),
                ('numeric_config', models.JSONField(blank=True, help_text='{"min": 0, "max": 10, "step": 1, "unit": "years"}', null=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.questionnaire')),
            ],
            options={
                'db_table': 'assessments_question',
                'ordering': ['questionnaire', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned'), ('TIMED_OUT', 'Timed Out')], db_index=True, default='IN_PROGRESS', max_length=20)),
                ('attempt_number', models.PositiveIntegerField(help_text='1-based attempt index for this profile+questionnaire')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='accounts.userprofile')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='assessments.questionnaire')),
            ],
            options={
                'db_table': 'responses_attempt',
            },
        ),
        migrations.CreateModel(
            name='AttemptScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_score', models.DecimalField(decimal_places=4, max_digits=10)),
                ('weighted_score', models.DecimalField(decimal_places=4, max_digits=10)),
                ('percentage', models.DecimalField(decimal_places=4, max_digits=6)),
                ('percentile_rank', models.DecimalField(blank=True, decimal_places=4, help_text='Async-computed. NULL until population data available.', max_digits=6, null=True)),
                ('scoring_engine_version', models.CharField(default='1.0.0', max_length=20)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='assessments.questionnaireattempt')),
            ],
            options={
                'db_table': 'scoring_attempt_score',
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupling_strength', models.DecimalField(decimal_places=4, default=1.0, help_text='0.0-1.0: how strongly this Q measures this tag', max_digits=5)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary tag drives the recommendation category')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.questionnaire')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tag')),
            ],
            options={
                'db_table': 'assessments_questionnaire_tag',
            },
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='tags',
            field=models.ManyToManyField(related_name='questionnaires', through='assessments.QuestionnaireTag', to='core.tag'),
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_value', models.JSONField()),
                ('points_awarded', models.DecimalField(blank=True, decimal_places=4, help_text='Populated by scoring engine after attempt completion', max_digits=8, null=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('time_taken_ms', models.PositiveIntegerField(blank=True, help_text='Milliseconds to answer — psychometric signal', null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='assessments.questionnaireattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='assessments.question')),
            ],
            options={
                'db_table': 'responses_question_response',
            },
        ),
        migrations.CreateModel(
            name='AnswerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_key', models.CharField(help_text='Stable key stored in responses, e.g. A/B/C/D or 1/2/3', max_length=10)),
                ('choice_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('partial_score', models.DecimalField(decimal_places=4, default=0, help_text='For Likert/partial credit. 0=wrong, 1=full credit', max_digits=6)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('explanation', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_choices', to='assessments.question')),
            ],
            options={
                'db_table': 'assessments_answer_choice',
                'ordering': ['question', 'order'],
                'constraints': [models.UniqueConstraint(fields=('question', 'choice_key'), name='uq_choice_question_key')],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['questionnaire', 'order'], name='assessments_questio_56d53a_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type'], name='assessments_questio_514fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='questionnaireattempt',
            index=models.Index(fields=['profile', 'questionnaire', 'status'], name='responses_a_profile_5460df_idx'),
        ),
        migrations.AddIndex(
            model_name='questionnaireattempt',
            index=models.Index(fields=['status', 'started_at'], name='responses_a_status_a38534_idx'),
        ),
        migrations.AddIndex(
            model_name='questionnaireattempt',
            index=models.Index(fields=['completed_at'], name='responses_a_complet_3db9bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionnaireattempt',
            constraint=models.UniqueConstraint(fields=('profile', 'questionnaire', 'attempt_number'), name='uq_attempt_profile_questionnaire_number'),
        ),
        migrations.AddIndex(
            model_name='attemptscore',
            index=models.Index(fields=['percentage'], name='scoring_att_percent_17236a_idx'),
        ),
        migrations.AddIndex(
            model_name='attemptscore',
            index=models.Index(fields=['percentile_rank'], name='scoring_att_percent_2e2c3b_idx'),
        ),
        migrations.AddIndex(
            model_name='questionnairetag',
            index=models.Index(fields=['tag', 'coupling_strength'], name='assessments_tag_id_5d917f_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionnairetag',
            constraint=models.UniqueConstraint(fields=('questionnaire', 'tag'), name='uq_qtag_questionnaire_tag'),
        ),
        migrations.AddIndex(
            model_name='questionnaire',
            index=models.Index(fields=['status', 'created_at'], name='assessments_status_064bc9_idx'),
        ),
        migrations.AddIndex(
            model_name='questionnaire',
            index=models.Index(fields=['slug', 'version_number'], name='assessments_slug_6f7809_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionnaire',
            constraint=models.UniqueConstraint(fields=('slug', 'version_number'), name='uq_questionnaire_slug_version'),
        ),
        migrations.AddIndex(
            model_name='questionresponse',
            index=models.Index(fields=['attempt'], name='responses_q_attempt_c4bfab_idx'),
        ),
        migrations.AddIndex(
            model_name='questionresponse',
            index=models.Index(fields=['question', 'is_correct'], name='responses_q_questio_cea859_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionresponse',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='uq_qresponse_attempt_question'),
        ),
    ]
