# Generated by Django 5.2.14 on 2026-06-03 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerchoice',
            name='partial_score',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='For Likert/partial credit. 0=wrong, 1=full credit', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='answerchoice',
            name='question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_choices', to='assessments.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.questionnaire'),
        ),
    ]
