# Generated by Django 5.2.14 on 2026-06-05 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_questionnaire_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='assessments.questionnaireattempt'),
        ),
    ]
