# Generated by Django 5.2.14 on 2026-06-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_alter_questionresponse_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireattempt',
            name='attempt_number',
            field=models.PositiveIntegerField(blank=True, help_text='1-based attempt index for this profile+questionnaire', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaireattempt',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
