# Generated by Django 5.2.14 on 2026-06-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_alter_questionnaireattempt_attempt_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptscore',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='attemptscore',
            name='scoring_engine_version',
            field=models.CharField(blank=True, default='1.0.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='questionnaireattempt',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
