# Generated by Django 5.2.14 on 2026-07-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_alter_attemptscore_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaireattempt',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
