# Generated by Django 5.2.14 on 2026-07-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_alter_questionnaireattempt_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
