# Generated by Django 5.2.14 on 2026-07-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_alter_questionnaire_status'),
        ('core', '0002_alter_tag_order_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questionnaires', through='assessments.QuestionnaireTag', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='questionnairetag',
            name='coupling_strength',
            field=models.DecimalField(blank=True, decimal_places=4, default=1.0, help_text='0.0-1.0: how strongly this Q measures this tag', max_digits=5),
        ),
    ]
