# Generated by Django 5.2.14 on 2026-07-16 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_alter_questionnaire_tags_and_more'),
        ('core', '0002_alter_tag_order_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairetag',
            name='tag',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.tag'),
        ),
    ]
