# Generated by Django 5.2.14 on 2026-07-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_alter_questionnairetag_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairetag',
            name='coupling_strength',
            field=models.DecimalField(blank=True, decimal_places=4, default=1.0, help_text='0.0-1.0: how strongly this Q measures this tag', max_digits=5, null=True),
        ),
    ]
