# Generated by Django 5.2.14 on 2026-05-18 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('color_hex', models.CharField(blank=True, max_length=7)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.tag')),
            ],
            options={
                'db_table': 'taxonomy_tag',
                'ordering': ['parent__title', 'order', 'title'],
                'indexes': [models.Index(fields=['slug'], name='taxonomy_ta_slug_a90815_idx'), models.Index(fields=['parent'], name='taxonomy_ta_parent__706f6e_idx')],
            },
        ),
    ]
