# Generated by Django 5.2.14 on 2026-07-20 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_alter_tag_order_alter_tag_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('RELATED', 'Related To'), ('PREREQUISITE', 'Prerequisite Of'), ('COMPLEMENTARY', 'Complementary To'), ('SYNONYM', 'Synonym Of'), ('CONFLICTING', 'Conflicts With')], db_index=True, max_length=20)),
                ('strength', models.DecimalField(decimal_places=4, default=1.0, help_text='0.0-1.0: how strong/confident this relationship is', max_digits=5)),
                ('is_symmetric', models.BooleanField(default=True, help_text='If True, the inverse row is auto-created/kept in sync')),
                ('is_system_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='core.tag')),
                ('to_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='core.tag')),
            ],
            options={
                'db_table': 'taxonomy_tag_relationship',
                'indexes': [models.Index(fields=['from_tag', 'relationship_type', '-strength'], name='taxonomy_ta_from_ta_2ce254_idx'), models.Index(fields=['to_tag', 'relationship_type'], name='taxonomy_ta_to_tag__3e2de5_idx')],
                'constraints': [models.UniqueConstraint(fields=('from_tag', 'to_tag', 'relationship_type'), name='uq_tagrel_from_to_type'), models.CheckConstraint(condition=models.Q(('from_tag', models.F('to_tag')), _negated=True), name='ck_tagrel_no_self_relationship')],
            },
        ),
        migrations.CreateModel(
            name='TagSourceMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SUBJECT', 'Subject'), ('QUESTIONNAIRE', 'Questionnaire'), ('QUESTION', 'Question'), ('CAREER_PSYCHOMETRIC', 'Career Psychometric Test'), ('MANUAL', 'Manually Curated'), ('SYSTEM_INFERRED', 'System Inferred')], db_index=True, max_length=30)),
                ('object_id', models.PositiveIntegerField()),
                ('confidence', models.DecimalField(decimal_places=4, default=1.0, help_text='0.0-1.0: confidence that this source genuinely evidences the tag', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_metadata', to='core.tag')),
            ],
            options={
                'db_table': 'taxonomy_tag_source_metadata',
                'indexes': [models.Index(fields=['tag', '-confidence'], name='taxonomy_ta_tag_id_e3cb0c_idx'), models.Index(fields=['content_type', 'object_id'], name='taxonomy_ta_content_ff1bf3_idx')],
                'constraints': [models.UniqueConstraint(fields=('tag', 'content_type', 'object_id'), name='uq_tagsource_tag_content_object')],
            },
        ),
    ]
