# Generated by Django 5.2.14 on 2026-06-15 06:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key; avoids exposing sequential IDs.', primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC timestamp of the request.  Partition key candidate.')),
                ('session_key', models.CharField(blank=True, help_text='Django session key.  NULL when session middleware is absent.', max_length=64, null=True)),
                ('ip_address', models.GenericIPAddressField(db_index=True, help_text='Client IP address, normalised by the tracking service.', unpack_ipv4=True)),
                ('path', models.CharField(help_text='Request path (without query string).', max_length=2048)),
                ('query_string', models.TextField(blank=True, default='', help_text='Raw query string, stored for future analysis.')),
                ('method', models.CharField(help_text='HTTP method in uppercase (GET, POST, …).', max_length=10)),
                ('status_code', models.PositiveSmallIntegerField(help_text='HTTP response status code.')),
                ('response_time_ms', models.PositiveIntegerField(blank=True, help_text='End-to-end response time in milliseconds.', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='Raw User-Agent header value.')),
                ('browser_family', models.CharField(blank=True, default='', help_text="Parsed browser family name (e.g. 'Chrome', 'Firefox').", max_length=128)),
                ('browser_version', models.CharField(blank=True, default='', help_text='Parsed browser version string.', max_length=32)),
                ('os_family', models.CharField(blank=True, default='', help_text='Parsed operating system family name.', max_length=128)),
                ('os_version', models.CharField(blank=True, default='', help_text='Parsed OS version string.', max_length=32)),
                ('device_type', models.CharField(blank=True, default='', help_text='Normalised device type: desktop, mobile, tablet, bot, unknown.', max_length=16)),
                ('is_ajax', models.BooleanField(default=False, help_text='True when X-Requested-With: XMLHttpRequest is present.')),
                ('is_secure', models.BooleanField(default=False, help_text='True when the request was served over HTTPS.')),
                ('referer', models.URLField(blank=True, default='', help_text='HTTP Referer header value.', max_length=2048)),
                ('country_code', models.CharField(blank=True, default='', help_text='ISO 3166-1 alpha-2 country code resolved from IP.', max_length=8)),
                ('city', models.CharField(blank=True, default='', help_text='City name resolved from IP.', max_length=128)),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user, or NULL for anonymous requests.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Activity',
                'verbose_name_plural': 'Site Activities',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='ra_activity_ts_idx'), models.Index(fields=['user', 'timestamp'], name='ra_activity_user_ts_idx'), models.Index(fields=['session_key', 'timestamp'], name='ra_activity_session_ts_idx'), models.Index(fields=['ip_address', 'timestamp'], name='ra_activity_ip_ts_idx'), models.Index(fields=['path', 'timestamp'], name='ra_activity_path_ts_idx'), models.Index(fields=['status_code', 'timestamp'], name='ra_activity_status_ts_idx'), models.Index(fields=['country_code', 'timestamp'], name='ra_activity_country_ts_idx'), models.Index(fields=['device_type', 'timestamp'], name='ra_activity_device_ts_idx'), models.Index(fields=['user', 'ip_address', 'timestamp'], name='ra_activity_user_ip_ts_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status_code__gte', 100), ('status_code__lte', 599)), name='ra_activity_valid_status_code'), models.CheckConstraint(condition=models.Q(('response_time_ms__isnull', True), ('response_time_ms__gte', 0), _connector='OR'), name='ra_activity_non_negative_response_time')],
            },
        ),
    ]
