# Generated by Django 5.2.14 on 2026-05-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(help_text='1=First choice, 4=Fourth choice (KUCCPS aligned)')),
            ],
            options={
                'db_table': 'accounts_career_preference',
            },
        ),
        migrations.CreateModel(
            name='ProfileSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'accounts_profile_subject',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('category', models.CharField(choices=[('SCIENCE', 'Science'), ('ARTS', 'Arts'), ('TECHNICAL', 'Technical'), ('LANGUAGE', 'Language')], db_index=True, max_length=50)),
                ('is_compulsory', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'accounts_subject',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('about_me', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/')),
            ],
            options={
                'db_table': 'accounts_profile',
            },
        ),
    ]
