# Generated by Django 5.2.14 on 2026-05-18 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('careers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='careerpreference',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_profiles', to='careers.career'),
        ),
        migrations.AddField(
            model_name='profilesubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.subject'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subjects',
            field=models.ManyToManyField(related_name='profiles', through='accounts.ProfileSubject', to='accounts.subject'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilesubject',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='careerpreference',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_preferences', to='accounts.userprofile'),
        ),
        migrations.AddConstraint(
            model_name='profilesubject',
            constraint=models.UniqueConstraint(fields=('profile', 'subject'), name='uq_profile_subject'),
        ),
        migrations.AddIndex(
            model_name='careerpreference',
            index=models.Index(fields=['profile', 'rank'], name='accounts_ca_profile_acc786_idx'),
        ),
        migrations.AddConstraint(
            model_name='careerpreference',
            constraint=models.UniqueConstraint(fields=('profile', 'rank'), name='uq_profile_career_rank'),
        ),
        migrations.AddConstraint(
            model_name='careerpreference',
            constraint=models.UniqueConstraint(fields=('profile', 'career'), name='uq_profile_career_choice'),
        ),
        migrations.AddConstraint(
            model_name='careerpreference',
            constraint=models.CheckConstraint(condition=models.Q(('rank__gte', 1), ('rank__lte', 4)), name='ck_career_preference_rank_range'),
        ),
    ]
