# Generated by Django 5.2.14 on 2026-07-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpreference',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1=First choice, 4=Fourth choice (KUCCPS aligned)'),
        ),
        migrations.AlterField(
            model_name='profilesubject',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='is_compulsory',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
    ]
