# Generated by Django 5.2.14 on 2026-07-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_careerpreference_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notification_settings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='remember_me',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
