# Generated by Django 5.2.14 on 2026-07-20 07:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_notification_settings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user', 'updated_at'], name='accounts_pr_user_id_e9f66c_idx'),
        ),
    ]
