"""
Default settings for ANALYTICS.

Each value is read from Django settings with a sensible default.
Import ``get_setting`` in application code to access configuration.
"""

from __future__ import annotations

import logging
from typing import Any, List

from django.conf import settings

from analytics.exceptions import ConfigurationError

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def get_setting(name: str, default: Any = None) -> Any:
    """
    Return the value of *name* from Django settings, falling back to *default*.

    Parameters
    ----------
    name:
        The settings key to look up.
    default:
        The value to return when the key is absent.

    Returns
    -------
    Any
        The configured value or the provided default.
    """
    return getattr(settings, name, default)


# ---------------------------------------------------------------------------
# Excluded paths
# ---------------------------------------------------------------------------

DEFAULT_EXCLUDED_PATHS: List[str] = [
    "/admin/",
    "/static/",
    "/media/",
    "/favicon.ico",
]


def get_excluded_paths() -> List[str]:
    """Return the list of URL path prefixes excluded from tracking."""
    return get_setting("ANALYTICS_EXCLUDED_PATHS", DEFAULT_EXCLUDED_PATHS)


# ---------------------------------------------------------------------------
# GeoIP
# ---------------------------------------------------------------------------


def get_geoip_enabled() -> bool:
    """Return whether GeoIP resolution is enabled."""
    return bool(get_setting("ANALYTICS_GEOIP_ENABLED", False))


def get_geoip_path() -> str:
    """Return the filesystem path to the GeoLite2-City.mmdb directory."""
    return str(get_setting("ANALYTICS_GEOIP_PATH", ""))


# ---------------------------------------------------------------------------
# Cache timeouts (seconds)
# ---------------------------------------------------------------------------

DEFAULT_CACHE_TIMEOUT: int = 300          # 5 minutes
DEFAULT_REALTIME_CACHE_TIMEOUT: int = 30  # 30 seconds
DEFAULT_GEOIP_CACHE_TIMEOUT: int = 86400  # 24 hours


def get_cache_timeout() -> int:
    """Return the default cache TTL in seconds for standard analytics."""
    return int(get_setting("ANALYTICS_CACHE_TIMEOUT", DEFAULT_CACHE_TIMEOUT))


def get_realtime_cache_timeout() -> int:
    """Return the cache TTL in seconds for realtime analytics."""
    return int(
        get_setting(
            "ANALYTICS_REALTIME_CACHE_TIMEOUT",
            DEFAULT_REALTIME_CACHE_TIMEOUT,
        )
    )


def get_geoip_cache_timeout() -> int:
    """Return the cache TTL in seconds for GeoIP lookups."""
    return int(
        get_setting("ANALYTICS_GEOIP_CACHE_TIMEOUT", DEFAULT_GEOIP_CACHE_TIMEOUT)
    )


# ---------------------------------------------------------------------------
# Cache key prefix
# ---------------------------------------------------------------------------

DEFAULT_CACHE_KEY_PREFIX: str = "ra"


def get_cache_key_prefix() -> str:
    """Return the prefix used for all cache keys generated by this application."""
    return str(get_setting("ANALYTICS_CACHE_KEY_PREFIX", DEFAULT_CACHE_KEY_PREFIX))


# ---------------------------------------------------------------------------
# Session timeout
# ---------------------------------------------------------------------------

DEFAULT_SESSION_TIMEOUT_MINUTES: int = 30


def get_session_timeout_minutes() -> int:
    """Return the session inactivity timeout in minutes."""
    return int(
        get_setting(
            "ANALYTICS_SESSION_TIMEOUT_MINUTES",
            DEFAULT_SESSION_TIMEOUT_MINUTES,
        )
    )


# ---------------------------------------------------------------------------
# Startup validation
# ---------------------------------------------------------------------------


def validate_settings() -> None:
    """
    Validate that the application settings are internally consistent.

    Raises
    ------
    ConfigurationError
        When GeoIP is enabled but no path has been configured.
    """
    if get_geoip_enabled() and not get_geoip_path():
        raise ConfigurationError(
            "ANALYTICS_GEOIP_ENABLED is True but "
            "ANALYTICS_GEOIP_PATH is not configured."
        )

    timeout = get_cache_timeout()
    if timeout < 0:
        raise ConfigurationError(
            "ANALYTICS_CACHE_TIMEOUT must be a non-negative integer."
        )

    session_timeout = get_session_timeout_minutes()
    if session_timeout <= 0:
        raise ConfigurationError(
            "ANALYTICS_SESSION_TIMEOUT_MINUTES must be a positive integer."
        )

    logger.debug("ANALYTICS settings validated successfully.")
